CREATE TABLE agendas (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(120) NOT NULL,
  description VARCHAR2(1000),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE voting_sessions (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agenda_id NUMBER NOT NULL,
  opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
  closes_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR2(20) NOT NULL,
  CONSTRAINT fk_voting_sessions_agenda FOREIGN KEY (agenda_id) REFERENCES agendas(id)
);

CREATE INDEX ix_sessions_agenda_status ON voting_sessions(agenda_id, status);
CREATE INDEX ix_sessions_closes_at ON voting_sessions(closes_at);

CREATE TABLE votes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agenda_id NUMBER NOT NULL,
  cpf VARCHAR2(11) NOT NULL,
  choice VARCHAR2(10) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_votes_agenda FOREIGN KEY (agenda_id) REFERENCES agendas(id),
  CONSTRAINT uk_votes_agenda_cpf UNIQUE (agenda_id, cpf)
);

CREATE INDEX ix_votes_agenda_choice ON votes(agenda_id, choice);
